version: "3.5"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo-back
        environment:
            # - PORT=3000
            - DB_URL=${DB_URL}
        # ports: 
        #     - "3000:3000" 
        volumes:
            - ./src:/app/src
