version: "3.5"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: ${ENV}
        container_name: todo-back
        environment:
            # - PORT=3000  # Port défini directement à 3000
            - ENV=local
            # - DB_HOST=${DB_HOST}
            # - DB_PORT=${DB_PORT}
            # - DB_USER=${DB_USER}
            # - DB_PASSWORD=${DB_PASSWORD}
            # - DB_DBNAME=${DB_DBNAME}
            - DB_URL=${DB_URL}
        # ports: 
        #     - "3001:3001" 
        volumes:
            - ./src:/app/src
