version: "3.5"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo-back
        environment:
            - DB_URL=${DB_URL}
        ports: 
            - "3000:3010" 
        volumes:
            - ./src:/app/src
